from typing import List, Tuple


def get_hole_positions(count: int, w: float, d: float) -> List[Tuple[float, float]]:
    """Compute hole center XY positions relative to plate center for N holes."""
    if count <= 0:
        return []
    if count == 1:
        return [(0.0, 0.0)]
    elif count == 2:
        return [(-w / 4.0, 0.0), (w / 4.0, 0.0)]
    elif count == 3:
        return [(-w / 3.0, 0.0), (0.0, 0.0), (w / 3.0, 0.0)]
    elif count == 4:
        sx, sy = w / 4.0, d / 4.0
        return [(-sx, -sy), (sx, -sy), (-sx, sy), (sx, sy)]
    else:
        cols = min(count, 4)
        rows = (count + cols - 1) // cols
        positions = []
        for row in range(rows):
            cols_in_row = min(cols, count - row * cols)
            for col in range(cols_in_row):
                x = (col - (cols_in_row - 1) / 2.0) * (w * 0.7 / max(cols_in_row - 1, 1))
                y = (row - (rows - 1) / 2.0) * (d * 0.7 / max(rows - 1, 1))
                positions.append((x, y))
        return positions


def generate_scad_code(params: dict) -> str:
    """Convert parsed CAD parameters to OpenSCAD code."""
    shapes = params.get("shapes", [])
    if not shapes:
        raise ValueError("형상 데이터가 없습니다.")

    parts = []
    z_top = 0.0  # top Z of the previous base shape

    for i, shape in enumerate(shapes):
        stype = shape.get("type")
        on_top = shape.get("on_top", False) and i > 0
        z = float(z_top) if on_top else 0.0

        if stype == "box":
            w = float(shape["width"])
            d = float(shape["depth"])
            h = float(shape["height"])
            parts.append(f"translate([{-w/2}, {-d/2}, {z}]) cube([{w}, {d}, {h}]);")
            z_top = z + h

        elif stype == "cylinder":
            r = float(shape.get("radius") or shape.get("diameter", 10) / 2)
            h = float(shape["height"])
            parts.append(f"translate([0, 0, {z}]) cylinder(h={h}, r={r}, $fn=64);")
            z_top = z + h

        elif stype == "sphere":
            r = float(shape.get("radius") or shape.get("diameter", 10) / 2)
            parts.append(f"translate([0, 0, {z + r}]) sphere(r={r}, $fn=64);")
            z_top = z + 2 * r

        elif stype == "plate_with_holes":
            w = float(shape["width"])
            d_val = float(shape["depth"])
            h = float(shape["height"])
            holes = shape.get("holes", [])

            hole_lines = []
            for hole in holes:
                hr = float(hole.get("radius") or hole.get("diameter", 10) / 2)
                count = int(hole.get("count", 1))
                for (hx, hy) in get_hole_positions(count, w, d_val):
                    hole_lines.append(
                        f"    translate([{hx}, {hy}, {z - 0.5}])"
                        f" cylinder(h={h + 1}, r={hr}, $fn=64);"
                    )

            plate = f"translate([{-w/2}, {-d_val/2}, {z}]) cube([{w}, {d_val}, {h}])"
            if hole_lines:
                inner_holes = "\n".join(hole_lines)
                parts.append(f"difference() {{\n  {plate};\n{inner_holes}\n}}")
            else:
                parts.append(f"{plate};")
            z_top = z + h

        else:
            raise ValueError(f"지원하지 않는 형상 타입: {stype}")

    header = "// Generated by NL-CAD MVP\n$fn = 64;\n\n"

    if len(parts) == 1:
        return header + parts[0] + "\n"
    else:
        inner = "\n  ".join(parts)
        return header + f"union() {{\n  {inner}\n}}\n"
