"""OpenSCAD code generator — recursively walks an IRTree and emits .scad source."""
from __future__ import annotations
from typing import List
from services.ir.schema import IRNode, IRTree
from services.generators.base import CADGenerator

_INDENT = "  "
_FN = 64   # $fn resolution for curved shapes


class OpenSCADGenerator(CADGenerator):

    def generate_code(self, ir: IRTree) -> str:
        header = f"// Generated by NL-CAD — IR v{ir.version}\n$fn = {_FN};\n\n"
        body = self._node(ir.root, depth=0)
        return header + body + "\n"

    def file_extension(self) -> str:
        return "scad"

    # ── recursive node renderer ───────────────────────────────────────────────

    def _node(self, node: IRNode, depth: int) -> str:
        pad = _INDENT * depth
        comment = f"  // {node.comment}" if node.comment else ""

        op = node.op

        # ── primitives ────────────────────────────────────────────────────────
        if op == "box":
            w = node.pf("width", 10)
            d = node.pf("depth", 10)
            h = node.pf("height", 10)
            c = "true" if node.p("center", False) else "false"
            return f"{pad}cube([{w}, {d}, {h}], center={c});{comment}"

        if op == "cylinder":
            h  = node.pf("height", 10)
            c  = "true" if node.p("center", False) else "false"
            if "r1" in node.params or "r2" in node.params:
                r1 = node.pf("r1", 5)
                r2 = node.pf("r2", 5)
                return f"{pad}cylinder(h={h}, r1={r1}, r2={r2}, center={c});{comment}"
            r = node.pf("radius", 5)
            return f"{pad}cylinder(h={h}, r={r}, center={c});{comment}"

        if op in ("sphere", "cone"):
            r = node.pf("radius", 5)
            return f"{pad}sphere(r={r});{comment}"

        # ── 2-D profiles ──────────────────────────────────────────────────────
        if op == "polygon" or op == "path":
            pts = node.p("points", [])
            pts_str = ", ".join(f"[{x},{y}]" for x, y in pts)
            return f"{pad}polygon(points=[{pts_str}]);{comment}"

        if op == "circle_2d":
            r = node.pf("radius", 5)
            return f"{pad}circle(r={r});{comment}"

        if op == "square_2d":
            w = node.pf("width", 10)
            h = node.pf("height", 10)
            c = "true" if node.p("center", False) else "false"
            return f"{pad}square([{w}, {h}], center={c});{comment}"

        # ── booleans ──────────────────────────────────────────────────────────
        if op in ("union", "difference", "intersection"):
            body = self._children_block(node.children, depth + 1)
            return f"{pad}{op}() {{{comment}\n{body}\n{pad}}}"

        # ── transforms ────────────────────────────────────────────────────────
        if op == "translate":
            x = node.pf("x"); y = node.pf("y"); z = node.pf("z")
            child = self._node(node.children[0], depth + 1) if node.children else ""
            return f"{pad}translate([{x}, {y}, {z}]){comment}\n{child}"

        if op == "rotate":
            x = node.pf("x"); y = node.pf("y"); z = node.pf("z")
            child = self._node(node.children[0], depth + 1) if node.children else ""
            return f"{pad}rotate([{x}, {y}, {z}]){comment}\n{child}"

        if op == "scale":
            x = node.pf("x", 1); y = node.pf("y", 1); z = node.pf("z", 1)
            child = self._node(node.children[0], depth + 1) if node.children else ""
            return f"{pad}scale([{x}, {y}, {z}]){comment}\n{child}"

        if op == "mirror":
            x = node.pf("x"); y = node.pf("y"); z = node.pf("z")
            child = self._node(node.children[0], depth + 1) if node.children else ""
            return f"{pad}mirror([{x}, {y}, {z}]){comment}\n{child}"

        # ── extrusions ────────────────────────────────────────────────────────
        if op == "linear_extrude":
            h     = node.pf("height", 1)
            twist = node.pf("twist", 0)
            scale = node.pf("scale", 1.0)
            ctr   = "true" if node.p("center", False) else "false"
            child = self._node(node.children[0], depth + 1) if node.children else ""
            return (
                f"{pad}linear_extrude(height={h}, twist={twist}, "
                f"scale={scale}, center={ctr}){comment}\n{child}"
            )

        if op == "rotate_extrude":
            angle = node.pf("angle", 360)
            child = self._node(node.children[0], depth + 1) if node.children else ""
            return f"{pad}rotate_extrude(angle={angle}){comment}\n{child}"

        # ── patterns ──────────────────────────────────────────────────────────
        if op == "linear_pattern":
            count   = int(node.p("count", 1))
            spacing = node.p("spacing", [0, 0, 0])
            dx, dy, dz = (float(spacing[i]) if i < len(spacing) else 0.0 for i in range(3))
            child   = self._node(node.children[0], depth + 2) if node.children else ""
            inner   = f"{_INDENT * (depth + 1)}translate([i*{dx}, i*{dy}, i*{dz}])\n{child}"
            return (
                f"{pad}for (i = [0:{count - 1}]) {{{comment}\n"
                f"{inner}\n"
                f"{pad}}}"
            )

        if op == "circular_pattern":
            count  = int(node.p("count", 1))
            radius = node.pf("radius", 10)
            child  = self._node(node.children[0], depth + 3) if node.children else ""
            p2     = _INDENT * (depth + 1)
            p3     = _INDENT * (depth + 2)
            return (
                f"{pad}for (i = [0:{count - 1}]) {{{comment}\n"
                f"{p2}rotate([0, 0, i * 360 / {count}])\n"
                f"{p3}translate([{radius}, 0, 0])\n"
                f"{child}\n"
                f"{pad}}}"
            )

        raise ValueError(f"OpenSCADGenerator: unknown op '{op}'")

    def _children_block(self, children: List[IRNode], depth: int) -> str:
        return "\n".join(self._node(c, depth) for c in children)
